cors:
  originPatterns: "http://localhost:8080"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MotorolaD3@
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
  devtools:
    livereload: false
spring-doc.pathsToMatch: /person/**, /book/**
